services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bin/rails server -b 0.0.0.0 -p 3000
    volumes:
      - .:/rails
      - rails_storage:/rails/storage
      - bundle_cache:/usr/local/bundle
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=development
      - OTEL_SERVICE_NAME=hotel-food-app
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
  otel-collector:
    image: otel/opentelemetry-collector-contrib
    container_name: otel-collector
    restart: unless-stopped
    command: ["--config=/etc/otelcol/config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol/config.yaml
      - ./traces.log:/var/log/traces.log:ro
    ports:
      - "4317:4317"
      - "8889:8889"
      - "4318:4318"
      - "8888:8888"
      - "8006:8006"
      - "13133:13133"
      - "1777:1777"
      - "55679:55679"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:13133"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  rails_storage:
  bundle_cache:
